spring:
  datasource:
    url: jdbc:postgresql://localhost:${MSPH_DEV_POSTGRESQL_PORT:7500}/msph_auth

moonsphere:
  openapi:
    service:
      title: Auth service
      version: 1.0.0
      url: http://localhost:${MSPH_DEV_API_GATEWAY_PORT:6055}

springdoc:
  api-docs:
    path: /auth-service/v3/api-docs
  swagger-ui:
    path: /auth-service/swagger-ui.html