server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:${MSPH_DEV_POSTGRESQL_PORT:7500}/msph_auth
  liquibase:
    contexts: lq_dev
  jpa:
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${MSPH_DEV_EUREKA_SERVER_PORT:8761}/eureka