spring:
  application:
    name: vsph-account-service
  profiles:
    group:
      dev:
        - 'microservice-dev'
        - 'postgresql-db'
        - 'postgresql-db-dev'
        - 'eureka-config'
      docker:
        - 'microservice-docker'
        - 'postgresql-db'
        - 'postgresql-db-docker'
        - 'eureka-config'
