server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://${V_EUREKA_USERNAME}:${V_EUREKA_PASSWORD}@vsph-discovery-server:8761/eureka

visphere:
  jwt:
    secret-key: ${V_JWT_SECRET_KEY}
    issuer: ${V_JWT_ISSUER}
    audience: ${V_JWT_AUDIENCE}
  external-service:
    landing-url: ${VSPH_LANDING_URL}
    client-url: ${VSPH_CLIENT_URL}
    infra-gateway-url: ${VSPH_API_GATEWAY_URL}
    s3-static-url: ${VSPH_STATIC_S3_URL}
    s3-url: ${VSPH_S3_URL}
  s3:
    url: http://vsph-s3:9000
    access-key: ${V_S3_USERNAME}
    secret-key: ${V_S3_PASSWORD}