spring:
  kafka:
    bootstrap-servers: localhost:9093
    ssl:
      trust-store-password: ${VSPH_KAFKA_BROKER_PASSWORD}
      key-store-password: ${VSPH_KAFKA_BROKER_PASSWORD}
      key-password: ${VSPH_KAFKA_BROKER_PASSWORD}
    consumer:
      group-id: vsph-local-g
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${VSPH_KAFKA_CLIENT_USERNAME}" password="${VSPH_KAFKA_CLIENT_PASSWORD}";

visphere:
  kafka:
    group-id: ${spring.kafka.consumer.group-id}
    topic:
      jwt-is-on-blacklist: local-jwt-is-on-blacklist
      check-user: local-check-user
      user-details: local-user-details
      persist-new-user: local-persist-new-user
      email-activate-account: local-email-activate-account
      email-new-account: local-email-new-account
      email-change-password: local-email-change-password
      email-password-changed: local-email-password-changed
      email-mfa-code: local-email-mfa-code
      generate-default-user-profile: local-generate-default-user-profile
      generate-default-guild-profile: local-generate-default-guild-profile
      update-default-guild-profile: local-update-default-guild-profile
      profile-image-details: local-profile-image-details