spring:
  kafka:
    bootstrap-servers: vsph-kafka-broker:9094
    ssl:
      trust-store-password: ${V_KAFKA_BROKER_PASSWORD}
      key-store-password: ${V_KAFKA_BROKER_PASSWORD}
      key-password: ${V_KAFKA_BROKER_PASSWORD}
    consumer:
      group-id: vsph-docker-g
      client-id: vsph-docker-c
    producer:
      client-id: vsph-docker-c
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${V_KAFKA_CLIENT_USERNAME}" password="${V_KAFKA_CLIENT_PASSWORD}";
      ssl:
        endpoint:
          identification:
            algorithm: ''