spring:
  kafka:
    bootstrap-servers: localhost:9093
    ssl:
      trust-store-password: ${VSPH_KAFKA_BROKER_PASSWORD}
      key-store-password: ${VSPH_KAFKA_BROKER_PASSWORD}
      key-password: ${VSPH_KAFKA_BROKER_PASSWORD}
    consumer:
      group-id: vsph-local-g
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${VSPH_KAFKA_CLIENT_USERNAME}" password="${VSPH_KAFKA_CLIENT_PASSWORD}";

visphere:
  kafka:
    group-id: ${spring.kafka.consumer.group-id}
    topic:
      jwt-is-on-blacklist: local-jwt-is-on-blacklist
      account-details: local-account-details
      create-user: local-create-user
      activate-user: local-activate-user
      check-user: local-check-user
      email-activate-account: local-email-activate-account
      email-change-password: local-email-change-password
      email-new-account: local-email-new-account
      generate-default-user-profile: local-generate-default-user-profile
      profile-image-details: local-profile-image-details