server:
  port: 0
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${VSPH_DEV_EUREKA_SERVER_PORT:8761}/eureka

visphere:
  jwt:
    secret-key: ${VSPH_JWT_SECRET_KEY}
    issuer: ${VSPH_JWT_ISSUER}
    audience: ${VSPH_JWT_AUDIENCE}