spring:
  kafka:
    bootstrap-servers: localhost:9093
    ssl:
      trust-store-password: ${VSPH_KAFKA_BROKER_PASSWORD}
      key-store-password: ${VSPH_KAFKA_BROKER_PASSWORD}
      key-password: ${VSPH_KAFKA_BROKER_PASSWORD}
    consumer:
      group-id: vsph-local-g
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${VSPH_KAFKA_CLIENT_USERNAME}" password="${VSPH_KAFKA_CLIENT_PASSWORD}";

visphere:
  kafka:
    group-id: ${spring.kafka.consumer.group-id}
    topic:
      jwt-is-on-blacklist: local-jwt-is-on-blacklist
      check-user: local-check-user
      user-details: local-user-details
      persist-new-user: local-persist-new-user
      get-oauth2-user-details: local-get-oauth2-user-details
      update-oauth2-user-details: local-update-oauth2-user-details
      login-oauth2-user: local-login-oauth2-user
      get-oauth2-details: local-get-oauth2-details
      email-activate-account: local-email-activate-account
      email-new-account: local-email-new-account
      email-change-password: local-email-change-password
      email-password-changed: local-email-password-changed
      email-mfa-code: local-email-mfa-code
      email-updated-mfa-state: local-email-updated-mfa-state
      email-reset-mfa-state: local-email-reset-mfa-state
      email-req-change-email: local-email-req-change-email
      email-req-change-second-email: local-email-req-change-second-email
      email-changed-email: local-email-changed-email
      email-changed-second-email: local-email-changed-second-email
      email-removed-second-email: local-email-removed-second-email
      email-enabled-account: local-email-enabled-account
      email-disabled-account: local-email-disabled-account
      email-deleted-account: local-email-deleted-account
      generate-default-user-profile: local-generate-default-user-profile
      replace-profile-image-with-locked: local-replace-profile-image-with-locked
      replace-locked-with-profile-image: local-replace-locked-with-profile-image
      generate-default-guild-profile: local-generate-default-guild-profile
      update-default-guild-profile: local-update-default-guild-profile
      profile-image-details: local-profile-image-details
      get-user-persisted-related-settings: local-get-user-persisted-related-settings
      instantiate-user-related-settings: local-instantiate-user-related-settings
      persist-notif-user-settings: local-persist-notif-user-settings
