spring:
  kafka:
    bootstrap-servers: vsph-kafka-broker:9094
    ssl:
      trust-store-password: ${V_KAFKA_BROKER_PASSWORD}
      key-store-password: ${V_KAFKA_BROKER_PASSWORD}
      key-password: ${V_KAFKA_BROKER_PASSWORD}
    consumer:
      group-id: vsph-docker-g
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${V_KAFKA_CLIENT_USERNAME}" password="${V_KAFKA_CLIENT_PASSWORD}";
      ssl:
        endpoint:
          identification:
            algorithm: ''

visphere:
  kafka:
    group-id: ${spring.kafka.consumer.group-id}
    topic:
      jwt-is-on-blacklist: docker-jwt-is-on-blacklist
      check-user: docker-check-user
      user-details: docker-user-details
      email-activate-account: docker-email-activate-account
      email-new-account: docker-email-new-account
      email-change-password: docker-email-change-password
      email-password-changed: docker-email-password-changed
      email-new-account: docker-email-new-account
      generate-default-user-profile: docker-generate-default-user-profile
      profile-image-details: docker-profile-image-details