spring:
  kafka:
    security:
      protocol: SASL_SSL
    ssl:
      trust-store-location: file:${VSPH_KAFKA_CERTS_CONTAINER}/kafka.truststore.jks
      key-store-location: file:${VSPH_KAFKA_CERTS_CONTAINER}/kafka.keystore.jks
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        partitions: 2
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    streams:
      replication-factor: 1
    jaas:
      enabled: true
    properties:
      sasl:
        mechanism: PLAIN