visphere:
  jwt:
    access:
      life-minutes: 5
    refresh:
      life-days: 30
  ota:
    life:
      activate-account-hours: 48
      change-password-minutes: 10
  s3:
    cdn-base-url: http://localhost:${VSPH_DEV_S3_PORT:8111}