spring:
  kafka:
    bootstrap-servers: vsph-kafka-broker:9094
    ssl:
      trust-store-password: ${V_KAFKA_BROKER_PASSWORD}
      key-store-password: ${V_KAFKA_BROKER_PASSWORD}
      key-password: ${V_KAFKA_BROKER_PASSWORD}
    consumer:
      group-id: vsph-docker-g
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${V_KAFKA_CLIENT_USERNAME}" password="${V_KAFKA_CLIENT_PASSWORD}";
      ssl:
        endpoint:
          identification:
            algorithm: ''

visphere:
  kafka:
    group-id: ${spring.kafka.consumer.group-id}
    topic:
      jwt-is-on-blacklist: docker-jwt-is-on-blacklist
      check-user: docker-check-user
      user-details: docker-user-details
      persist-new-user: docker-persist-new-user
      get-oauth2-user-details: docker-get-oauth2-user-details
      update-oauth2-user-details: docker-update-oauth2-user-details
      login-oauth2-user: docker-login-oauth2-user
      get-oauth2-details: docker-get-oauth2-details
      email-activate-account: docker-email-activate-account
      email-new-account: docker-email-new-account
      email-change-password: docker-email-change-password
      email-password-changed: docker-email-password-changed
      email-new-account: docker-email-new-account
      email-mfa-code: docker-email-mfa-code
      email-updated-mfa-state: docker-email-updated-mfa-state
      email-reset-mfa-state: docker-email-reset-mfa-state
      email-req-change-email: docker-email-req-change-email
      email-req-change-second-email: docker-email-req-change-second-email
      email-changed-email: docker-email-changed-email
      email-changed-second-email: docker-email-changed-second-email
      email-removed-second-email: docker-email-removed-second-email
      email-enabled-account: docker-email-enabled-account
      email-disabled-account: docker-email-disabled-account
      email-deleted-account: docker-email-deleted-account
      generate-default-user-profile: docker-generate-default-user-profile
      update-default-user-profile: docker-update-default-user-profile
      replace-profile-image-with-locked: docker-replace-profile-image-with-locked
      replace-locked-with-profile-image: docker-replace-locked-with-profile-image
      generate-default-guild-profile: docker-generate-default-guild-profile
      update-default-guild-profile: docker-update-default-guild-profile
      profile-image-details: docker-profile-image-details
      get-user-persisted-related-settings: docker-get-user-persisted-related-settings
      instantiate-user-related-settings: docker-instantiate-user-related-settings
      persist-notif-user-settings: docker-persist-notif-user-settings
      get-guild-images-by-guild-ids: docker-get-guild-images-by-guild-ids
      get-guild-profile-image-details: docker-get-guild-profile-image-details
      get-guild-details: docker-get-guild-details
      check-user-crendetials: docker-check-user-crendetials
      check-user-sphere-guilds: docker-check-user-sphere-guilds
      delete-user-image-data: docker-delete-user-image-data
      delete-guild-image-data: docker-delete-guild-image-data
      delete-oauth2-user-data: docker-delete-oauth2-user-data
      delete-user-settings-data: docker-delete-user-settings-data
      delete-notif-user-settings: docker-delete-notif-user-settings
      check-user-session: docker-check-user-session
      check-user-guild-assignments: docker-check-user-guild-assignments
      check-text-channel-assignments: docker-check-text-channel-assignments
      get-users-details: docker-get-users-details
      get-users-images-details: docker-get-users-images-details
      get-oauth2-users-details: docker-get-oauth2-users-details
      delete-user-messages: docker-delete-user-messages
      delete-text-channel-messages: docker-delete-text-channel-messages