spring:
  mvc:
    log-resolved-exception: false
    throw-exception-if-no-handler-found: true
  banner:
    location: classpath:spring/banner.txt
  jackson:
    deserialization:
      USE_LONG_FOR_INTS: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env
  endpoint:
    env:
      post:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
