spring:
  mvc:
    log-resolved-exception: false
    throw-exception-if-no-handler-found: true
  banner:
    location: classpath:spring/banner.txt
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 120MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env
  endpoint:
    env:
      post:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
