spring:
  application:
    name: msph-misc-service
  banner:
    location: classpath:spring/banner.txt

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

management:
  tracing:
    sampling:
      probability: 1.0