server:
  port: 0

spring:
  mail:
    port: ${MSPH_DEV_MAILHOG_PORT:1025}
    host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${MSPH_DEV_EUREKA_SERVER_PORT:8761}/eureka