spring:
  application:
    name: msph-discovery-server
  banner:
    location: classpath:spring/banner.txt

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

server:
  port: 6161