server:
  port: 8761

eureka:
  instance:
    hostname: msph-discovery-server
  client:
    service-url:
      defaultZone: http://${V_EUREKA_USERNAME}:${V_EUREKA_PASSWORD}@msph-discovery-server:${server.port}/eureka/

spring:
  security:
    user:
      name: ${V_EUREKA_USERNAME}
      password: ${V_EUREKA_PASSWORD}