spring:
  application:
    name: msph-misc-service
  banner:
    location: classpath:spring/banner.txt

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

application:
  captcha:
    secretkey: ${MSPH_CAPTCHA_SECRETKEY}

management:
  tracing:
    sampling:
      probability: 1.0