server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://msph-auth-service-db:5432/msph_auth_service_db

eureka:
  client:
    service-url:
      defaultZone: http://${V_EUREKA_USERNAME}:${V_EUREKA_PASSWORD}@msph-discovery-server:8761/eureka