server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://msph-account-service-db:5432/msph_account_service_db
  liquibase:
    contexts: lq_docker

eureka:
  client:
    service-url:
      defaultZone: http://${V_EUREKA_USERNAME}:${V_EUREKA_PASSWORD}@msph-discovery-server:8761/eureka