spring:
  application:
    name: msph-discovery-server
  banner:
    location: classpath:spring/banner.txt

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true