spring:
  application:
    name: msph-auth-service
  banner:
    location: classpath:spring/banner.txt

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1.0