spring:
  application:
    name: msph-misc-service
  cloud:
    vault:
      uri: http://localhost:8200
      token: ${ENV_MSPH_VAULT_TOKEN}
      authentication: TOKEN
      kv:
        backend: moonsphere
        default-context: ${spring.application.name}
  banner:
    location: classpath:spring/banner.txt

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 20

application:
  captcha:
    secretKey: ${V_CAPTCHA_SECRET_KEY}
    devSiteKey: ${V_CAPTCHA_SITE_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env
  endpoint:
    env:
      post:
        enabled: true
  tracing:
    sampling:
      probability: 1.0