server:
  port: ${MSPH_DOCKER_EUREKA_PORT}

eureka:
  instance:
    hostname: msph-discovery-server
  client:
    service-url:
      defaultZone: http://${MSPH_EUREKA_USERNAME}:${MSPH_EUREKA_PASSWORD}@msph-discovery-server:${server.port}/eureka/

spring:
  security:
    user:
      name: ${MSPH_EUREKA_USERNAME}
      password: ${MSPH_EUREKA_PASSWORD}