spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '${MSPH_DOCKER_FRONTEND_URL:http://localhost:4200}'

server:
  port: ${MSPH_DOCKER_API_GATEWAY_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: http://msph-discovery-server:${MSPH_DOCKER_EUREKA_PORT:8761}/eureka