server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:${MSPH_DEV_ACCOUNT_POSTGRES_PORT:7501}/msph_account_service_db
  jpa:
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${MSPH_DEV_EUREKA_SERVER_PORT:8761}/eureka