spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:${MSPH_DOCKER_LANDING_PORT}'
              - 'http://localhost:${MSPH_DOCKER_CLIENT_PORT}'

server:
  port: ${MSPH_DOCKER_API_GATEWAY_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: http://msph-discovery-server:${MSPH_DOCKER_EUREKA_PORT}/eureka