spring:
  application:
    name: msph-auth-service
  datasource:
    username: ${V_POSTGRES_USERNAME}
    password: ${V_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    log-resolved-exception: false
    throw-exception-if-no-handler-found: true
  liquibase:
    enabled: true
    change-log: classpath: db/changelog/db.changelog.cfg.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  banner:
    location: classpath:spring/banner.txt

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 20

management:
  tracing:
    sampling:
      probability: 1.0