spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:${ENV_DEV_MSPH_LANDING_PORT}'
              - 'http://localhost:${ENV_DEV_MSPH_CLIENT_PORT}'

server:
  port: ${ENV_DEV_MSPH_API_GATEWAY_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${ENV_DEV_MSPH_DISCOVERY_SERVER_PORT}/eureka