spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '${MSPH_FRONTEND_URL:http://localhost:4200}'

server:
  port: ${MSPH_API_GATEWAY_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${MSPH_EUREKA_PORT:8761}/eureka