spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirectUri: ${VSPH_API_GATEWAY_URL}/oauth2/callback
          facebook:
            redirectUri: ${VSPH_API_GATEWAY_URL}/oauth2/callback