spring:
  datasource:
    url: jdbc:postgresql://vsph-postgresql-db:5432/vsph_oauth2_client
  security:
    oauth2:
      client:
        registration:
          google:
            redirectUri: ${VSPH_API_GATEWAY_URL}/oauth2/callback
          facebook:
            redirectUri: ${VSPH_API_GATEWAY_URL}/oauth2/callback

visphere:
  oauth2:
    authorized-client-redirect-uris:
      - ${VSPH_CLIENT_URL}