spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${VSPH_API_GATEWAY_URL}/oauth2/callback
          facebook:
            redirect-uri: ${VSPH_API_GATEWAY_URL}/oauth2/callback