spring:
  application:
    name: vsph-m-oauth2-client-service
  profiles:
    group:
      dev:
        - 'microservice'
        - 'microservice-dev'
        - 'postgresql-db'
        - 'postgresql-db-dev'
        - 'kafka'
        - 'kafka-dev'
        - 'eureka-config'
      docker:
        - 'microservice'
        - 'microservice-docker'
        - 'postgresql-db'
        - 'postgresql-db-docker'
        - 'kafka'
        - 'kafka-docker'
        - 'eureka-config'
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${V_OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${V_OAUTH2_GOOGLE_CLIENT_SECRET}
          facebook:
            client-id: ${V_OAUTH2_FACEBOOK_CLIENT_ID}
            client-secret: ${V_OAUTH2_FACEBOOK_CLIENT_SECRET}
        provider:
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=id,first_name,last_name,email,picture.width(250).height(250)

visphere:
  oauth2:
    suppliers:
      - google
      - facebook
    expiration-minutes: 3
    spring-security-redirect-uri: /oauth2/callback
  kafka:
    reply-topic:
      user-details: user-details
      persist-new-user: persist-new-user
      get-oauth2-user-details: get-oauth2-user-details
      update-oauth2-user-details: update-oauth2-user-details
      login-oauth2-user: login-oauth2-user
      get-user-persisted-related-settings: get-user-persisted-related-settings
      instantiate-user-related-settings: instantiate-user-related-settings
      generate-default-user-profile: generate-default-user-profile
      replace-locked-with-profile-image: replace-locked-with-profile-image
      profile-image-details: profile-image-details