spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirectUri: http://localhost:${VSPH_DEV_API_GATEWAY_PORT}/oauth2/callback
          facebook:
            redirectUri: http://localhost:${VSPH_DEV_API_GATEWAY_PORT}/oauth2/callback

visphere:
  openapi:
    service:
      title: OAuth2 Client service
      version: 1.0.0
      url: http://localhost:${VSPH_DEV_API_GATEWAY_PORT:6055}