spring:
  cassandra:
    contact-points: localhost
    port: 9042
    username: ${VSPH_CASSANDRA_USERNAME}
    password: ${VSPH_CASSANDRA_PASSWORD}

visphere:
  openapi:
    service:
      title: Chat service
      version: 1.0.0
      url: http://localhost:${VSPH_DEV_API_GATEWAY_PORT:6055}

springdoc:
  api-docs:
    path: /vsph-m-chat-service/v3/api-docs
  swagger-ui:
    path: /vsph-m-chat-service/swagger-ui.html