spring:
  application:
    name: vsph-m-chat-service
  profiles:
    group:
      dev:
        - 'microservice'
        - 'microservice-dev'
        - 'eureka-config'
        - 'kafka'
        - 'kafka-dev'
      docker:
        - 'microservice'
        - 'microservice-docker'
        - 'eureka-config'
        - 'kafka'
        - 'kafka-docker'
  data:
    cassandra:
      keyspace-name: vsph_default_kspc
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s