spring:
  application:
    name: vsph-m-chat-service
  profiles:
    group:
      dev:
        - 'microservice'
        - 'microservice-dev'
        - 'eureka-config'
        - 'kafka'
        - 'kafka-dev'
      docker:
        - 'microservice'
        - 'microservice-docker'
        - 'eureka-config'
        - 'kafka'
        - 'kafka-docker'
  cassandra:
    keyspace-name: vsph_default_kspc
    schema-action: create-if-not-exists
    local-datacenter: datacenter1
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s

visphere:
  websocket:
    relay-host: localhost
  files:
    max-per-message: 5
  kafka:
    reply-topic:
      check-user-session: check-user-session
      check-user-guild-assignments: check-user-guild-assignments
      check-text-channel-assignments: check-text-channel-assignments
      get-users-details: get-users-details
      get-users-images-details: get-users-images-details
      get-guild-base-text-channel-id: get-guild-base-text-channel-id
      get-guild-details: get-guild-details
      get-user-text-channels: get-user-text-channels