spring:
  application:
    name: vsph-m-sphere-service
  profiles:
    group:
      dev:
        - 'microservice'
        - 'microservice-dev'
        - 'postgresql-db'
        - 'postgresql-db-dev'
        - 'kafka'
        - 'kafka-dev'
        - 'eureka-config'
      docker:
        - 'microservice'
        - 'microservice-docker'
        - 'postgresql-db'
        - 'postgresql-db-docker'
        - 'kafka'
        - 'kafka-docker'
        - 'eureka-config'

visphere:
  kafka:
    reply-topic:
      generate-default-guild-profile: generate-default-guild-profile
      update-default-guild-profile: update-default-guild-profile
      get-guild-images-by-guild-ids: get-guild-images-by-guild-ids
      get-guild-profile-image-details: get-guild-profile-image-details
      user-details: user-details
      profile-image-details: profile-image-details
      check-user-crendetials: check-user-crendetials
      delete-guild-image-data: delete-guild-image-data
      delete-user-messages: delete-user-messages
      delete-text-channel-messages: delete-text-channel-messages