spring:
  datasource:
    url: jdbc:postgresql://localhost:${VSPH_DEV_POSTGRESQL_PORT:7500}/vsph_sphere

visphere:
  openapi:
    service:
      title: Sphere service
      version: 1.0.0
      url: http://localhost:${VSPH_DEV_API_GATEWAY_PORT:6055}
  guild-link:
    url-prefix: http://localhost:${VSPH_DEV_CLIENT_PORT}

springdoc:
  api-docs:
    path: /vsph-m-sphere-service/v3/api-docs
  swagger-ui:
    path: /vsph-m-sphere-service/swagger-ui.html