spring:
  datasource:
    url: jdbc:postgresql://localhost:${MSPH_DEV_POSTGRESQL_PORT:7500}/msph_account

moonsphere:
  openapi:
    service:
      title: Account service
      version: 1.0.0
      url: http://localhost:${MSPH_DEV_API_GATEWAY_PORT:6055}

springdoc:
  api-docs:
    path: /account-service/v3/api-docs
  swagger-ui:
    path: /account-service/swagger-ui.html