spring:
  application:
    name: msph-api-gateway
  banner:
    location: classpath:spring/banner.txt
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account
          uri: lb://msph-account-service
          predicates:
            - Path=/api/v1/account/**
        - id: auth
          uri: lb://msph-auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: misc
          uri: lb://msph-misc-service
          predicates:
            - Path=/api/v1/misc/**
        - id: notification
          uri: lb://msph-notification-service
          predicates:
            - Path=/api/v1/notification/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 20

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env
  endpoint:
    env:
      post:
        enabled: true
  tracing:
    sampling:
      probability: 1.0