spring:
  application:
    name: msph-api-gateway
  profiles:
    group:
      dev:
        - 'eureka-config'
      docker:
        - 'eureka-config'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account
          uri: lb://msph-account-service
          predicates:
            - Path=/api/v1/account/**
        - id: auth
          uri: lb://msph-auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: misc
          uri: lb://msph-misc-service
          predicates:
            - Path=/api/v1/misc/**
        - id: multimedia
          uri: lb://msph-multimedia-service
          predicates:
            - Path=/api/v1/multimedia/**
        - id: notification
          uri: lb://msph-notification-service
          predicates:
            - Path=/api/v1/notification/**

moonsphere:
  i18n:
    availableLanguages: pl,en-US
    defaultLanguage: pl