spring:
  application:
    name: msph-discovery-server
  banner:
    location: classpath:spring/banner.txt

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env
  endpoint:
    env:
      post:
        enabled: true
  tracing:
    sampling:
      probability: 1.0