spring:
  datasource:
    url: jdbc:postgresql://localhost:${VSPH_DEV_POSTGRESQL_PORT:7500}/vsph_auth

visphere:
  openapi:
    service:
      title: Auth service
      version: 1.0.0
      url: http://localhost:${VSPH_DEV_API_GATEWAY_PORT:6055}
  jwt:
    secret-key: ${VSPH_JWT_SECRET_KEY}
    issuer: ${VSPH_JWT_ISSUER}
    audience: ${VSPH_JWT_AUDIENCE}

springdoc:
  api-docs:
    path: /vsph-auth-service/v3/api-docs
  swagger-ui:
    path: /vsph-auth-service/swagger-ui.html