spring:
  application:
    name: msph-notification-service
  profiles:
    default: 'eureka'
    # group:
    #   dev:
    #     - 'eureka'
    #   docker:
    #     - 'eureka'
  mail:
    protocol: smtp
    username: 'mailhoguser'
    password: 'root'
    properties:
      smtp:
        starttls:
          required: false
      mail:
        smtp:
          ssl:
            enable: false
          auth: false
          starttls:
            enable: false