spring:
  mail:
    port: ${MSPH_DEV_MAILHOG_PORT:7600}
    host: localhost

moonsphere:
  openapi:
    service:
      title: Notification service
      version: 1.0.0
      url: http://localhost:${MSPH_DEV_API_GATEWAY_PORT:6055}

springdoc:
  api-docs:
    path: /msph-notification-service/v3/api-docs
  swagger-ui:
    path: /msph-notification-service/swagger-ui.html