spring:
  application:
    name: msph-notification-service
  profiles:
    group:
      dev:
        - 'microservice-dev'
        - 'eureka-config'
      docker:
        - 'microservice-docker'
        - 'eureka-config'
  mail:
    protocol: smtp
    username: 'mailhoguser'
    password: 'root'
    properties:
      smtp:
        starttls:
          required: false
      mail:
        smtp:
          ssl:
            enable: false
          auth: false
          starttls:
            enable: false