spring:
  datasource:
    url: jdbc:postgresql://localhost:${VSPH_DEV_POSTGRESQL_PORT:7500}/vsph_multimedia

visphere:
  openapi:
    service:
      title: Multimedia service
      version: 1.0.0
      url: http://localhost:${VSPH_DEV_API_GATEWAY_PORT:6055}

springdoc:
  api-docs:
    path: /vsph-m-multimedia-service/v3/api-docs
  swagger-ui:
    path: /vsph-m-multimedia-service/swagger-ui.html