spring:
  application:
    name: msph-multimedia-service
  profiles:
    group:
      dev:
        - 'microservice-dev'
        - 'eureka-config'
      docker:
        - 'microservice-docker'
        - 'eureka-config'

moonsphere:
  captcha:
    secretKey: ${V_CAPTCHA_SECRET_KEY}
    devSiteKey: ${V_CAPTCHA_SITE_KEY}
