spring:
  application:
    name: vsph-api-gateway
  profiles:
    group:
      dev:
        - 'eureka-config'
      docker:
        - 'eureka-config'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://vsph-auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: misc
          uri: lb://vsph-misc-service
          predicates:
            - Path=/api/v1/misc/**
        - id: multimedia
          uri: lb://vsph-multimedia-service
          predicates:
            - Path=/api/v1/multimedia/**
        - id: notification
          uri: lb://vsph-notification-service
          predicates:
            - Path=/api/v1/notification/**

visphere:
  i18n:
    availableLanguages: pl,en-US
    defaultLanguage: pl