spring:
  application:
    name: vsph-api-gateway
  profiles:
    group:
      dev:
        - 'eureka-config'
      docker:
        - 'eureka-config'
  cloud:
    gateway:
      filter:
        remove-non-proxy-headers:
          headers:
          - dummy
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://vsph-m-user-service
          predicates:
            - Path=/api/v1/user/**
        - id: misc
          uri: lb://vsph-m-misc-service
          predicates:
            - Path=/api/v1/misc/**
        - id: multimedia
          uri: lb://vsph-m-multimedia-service
          predicates:
            - Path=/api/v1/multimedia/**
        - id: notification
          uri: lb://vsph-m-notification-service
          predicates:
            - Path=/api/v1/notification/**
        - id: oauth2
          uri: lb://vsph-m-oauth2-client-service
          predicates:
            - Path=/api/v1/oauth2/**, /oauth2/**
        - id: settings
          uri: lb://vsph-m-settings-service
          predicates:
            - Path=/api/v1/settings/**
        - id: sphere
          uri: lb://vsph-m-sphere-service
          predicates:
            - Path=/api/v1/sphere/**
        - id: chat
          uri: lb://vsph-m-chat-service
          predicates:
            - Path=/api/v1/chat/**
        - id: chat-ws
          uri: lb:ws://vsph-m-chat-service
          predicates:
            - Path=/ws/chat/**

visphere:
  i18n:
    availableLanguages: pl,en-US
    defaultLanguage: pl