spring:
  datasource:
    url: jdbc:postgresql://vsph-postgresql-db:5432/vsph_notification
  mail:
    port: 1025
    host: vsph-mailhog

visphere:
  mjml:
    api:
      host: ${VSPH_MAIL_PARSER_API_URL}
      header-key-signature: ${V_MAIL_PARSER_API_HEADER:x-vsph-mail-parser-key}
      api-key: ${V_MAIL_PARSER_API_KEY}
  mail:
    send-from: noreply@visphere.pl