spring:
  application:
    name: vsph-m-notification-service
  profiles:
    group:
      dev:
        - 'microservice'
        - 'microservice-dev'
        - 'postgresql-db'
        - 'postgresql-db-dev'
        - 'kafka'
        - 'kafka-dev'
        - 'eureka-config'
      docker:
        - 'microservice'
        - 'microservice-docker'
        - 'postgresql-db'
        - 'postgresql-db-docker'
        - 'kafka'
        - 'kafka-docker'
        - 'eureka-config'
  mail:
    protocol: smtp
    username: 'mailhoguser'
    password: 'root'
    properties:
      smtp:
        starttls:
          required: false
      mail:
        smtp:
          ssl:
            enable: false
          auth: false
          starttls:
            enable: false

visphere:
  hbs:
    templates-path: classpath:mail/templates
    layouts-path: classpath:mail/layouts
    extension: .hbs
    font-name: Figtree
    font-resource-path: https://fonts.googleapis.com/css2?family=Figtree
    mobile:
      app-gallery-link: https://appgallery.huawei.com
      app-store-link: https://www.apple.com/app-store
      google-play-link: https://play.google.com/store
    social:
      facebook-link: https://facebook.com
      youtube-link: https://youtube.com
      instagram-link: https://instagram.com
      x-link: https://twitter.com
      tiktok-link: https://tiktok.com
  mail:
    app-name: Visphere
    reply-to: info@visphere.pl
  kafka:
    reply-topic:
      get-oauth2-details: get-oauth2-details
      profile-image-details: profile-image-details