spring:
  datasource:
    url: jdbc:postgresql://localhost:${VSPH_DEV_POSTGRESQL_PORT:7500}/vsph_notification
  mail:
    port: ${VSPH_DEV_MAILHOG_PORT:7600}
    host: localhost

visphere:
  openapi:
    service:
      title: Notification service
      version: 1.0.0
      url: http://localhost:${VSPH_DEV_API_GATEWAY_PORT:6055}
  hbs:
    landing-url: http://localhost:${VSPH_DEV_LANDING_PORT}
    client-url: http://localhost:${VSPH_DEV_CLIENT_PORT}
  mjml:
    api:
      host: http://localhost:${VSPH_DEV_MAIL_PARSER_API_PORT}
      header-key-signature: ${ENV_MAIL_PARSER_API_HEADER:x-vsph-mail-parser-key}
      api-key: ${ENV_MAIL_PARSER_API_KEY}
  mail:
    send-from: DEVELOP-NOREPLY@visphere.pl

springdoc:
  api-docs:
    path: /vsph-m-notification-service/v3/api-docs
  swagger-ui:
    path: /vsph-m-notification-service/swagger-ui.html