spring:
  application:
    name: vsph-multimedia-service
  profiles:
    group:
      dev:
        - 'microservice-dev'
        - 'kafka'
        - 'kafka-dev'
        - 'eureka-config'
      docker:
        - 'microservice-docker'
        - 'kafka'
        - 'kafka-docker'
        - 'eureka-config'