spring:
  application:
    name: vsph-m-auth-service
  profiles:
    group:
      dev:
        - 'microservice'
        - 'microservice-dev'
        - 'postgresql-db'
        - 'postgresql-db-dev'
        - 'kafka'
        - 'kafka-dev'
        - 'eureka-config'
      docker:
        - 'microservice'
        - 'microservice-docker'
        - 'postgresql-db'
        - 'postgresql-db-docker'
        - 'kafka'
        - 'kafka-docker'
        - 'eureka-config'

visphere:
  kafka:
    reply-topic:
      generate-default-user-profile: generate-default-user-profile
      update-default-user-profile: update-default-user-profile
      profile-image-details: profile-image-details
      get-oauth2-details: get-oauth2-details
      get-user-persisted-related-settings: get-user-persisted-related-settings
      instantiate-user-related-settings: instantiate-user-related-settings
      replace-profile-image-with-locked: replace-profile-image-with-locked
      replace-locked-with-profile-image: replace-locked-with-profile-image
      persist-notif-user-settings: persist-notif-user-settings
  mfa:
    label: Visphere
    issuer: app@visphere.pl